// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "controlcm.h"

/////////////////////////////////////////////////////////////////////////////
// CControlCM

IMPLEMENT_DYNCREATE(CControlCM, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CControlCM properties

/////////////////////////////////////////////////////////////////////////////
// CControlCM operations

short CControlCM::GetComport()
{
	short result;
	InvokeHelper(0x68030000, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void CControlCM::SetComport(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x68030000, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

void CControlCM::ResetCom()
{
	InvokeHelper(0x6003000f, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CControlCM::Exec(BSTR* housecode, BSTR* devicecode, short* command, short* brightness)
{
	static BYTE parms[] =
		VTS_PBSTR VTS_PBSTR VTS_PI2 VTS_PI2;
	InvokeHelper(0x60030007, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 housecode, devicecode, command, brightness);
}

short CControlCM::Init()
{
	short result;
	InvokeHelper(0x6003000a, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}
