//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Vision2000.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VISION2000_DIALOG           102
#define IDR_VISION2000                  104
#define IDS_PROPSHT_CAPTION             105
#define IDD_PROPPAGE1                   106
#define IDD_PROPPAGE2                   107
#define IDD_PROPPAGE3                   108
#define IDD_PROPPAGE4                   109
#define IDD_PROPPAGE5                   110
#define IDD_PROPPAGE6                   111
#define IDD_PROPPAGE7                   112
#define IDD_PROPPAGE8                   113
#define IDR_MAINFRAME                   128
#define IDR_POPUP_MENU                  129
#define IDD_CONTROL_SHEET               133
#define IDD_CAMERA_CONTROL_PAGE         134
#define IDD_VCR_CONTROL_PAGE            135
#define IDD_CALL_CONTROL_PAGE           136
#define IDD_DIALOG1                     138
#define IDI_ICON_VCR                    141
#define IDI_ICON_FF                     142
#define IDI_ICON_POWER                  143
#define IDI_ICON_REC                    144
#define IDI_ICON_PAUSE                  145
#define IDI_ICON_REW                    146
#define IDI_ICON_STOP                   147
#define IDI_ICON_PLAY                   148
#define IDB_REW_U                       150
#define IDB_FF_U                        151
#define IDB_PAUSE_U                     152
#define IDB_PLAY_U                      153
#define IDB_POWER_U                     154
#define IDB_REC_U                       155
#define IDB_STOP_D                      156
#define IDB_VCR_U                       157
#define IDB_VIDEOCAMERA_U_BAK           159
#define IDB_FF_D                        160
#define IDB_VIDEOCAMERA_D_BAK           161
#define IDB_PAUSE_D                     162
#define IDB_PLAY_D                      163
#define IDB_POWER_D                     165
#define IDB_REC_D                       166
#define IDB_REW_D                       167
#define IDB_STOP_U                      168
#define IDB_VCR_D                       169
#define IDB_VISION2000                  172
#define IDI_VISION2000                  174
#define IDD_IR_CONTROL_PAGE             175
#define IDB_FF_X                        177
#define IDB_PAUSE_X                     178
#define IDB_PLAY_X                      179
#define IDB_POWER_X                     180
#define IDB_REC_X                       181
#define IDB_REW_X                       182
#define IDB_STOP_X                      183
#define IDB_VCR_X                       184
#define IDB_VIDEOCAMERA_X_BAK           185
#define IDD_SETTINGS_PAGE               186
#define IDB_CAMERA_SMALL_U              188
#define IDB_CAMERA_SMALL_D              189
#define IDI_SMALL_CAMERA                190
#define IDB_BITMAP1_U                   191
#define IDB_BITMAP1_D                   192
#define IDB_VIDEOCAMERA                 194
#define IDB_VIDEOCAMERA_U               194
#define IDB_VIDEOCAMERA_D               195
#define IDB_VIDEOCAMERA_X               196
#define IDC_MACHINENAME                 1000
#define IDC_CALLHANGUP                  1001
#define IDC_DATA                        1002
#define IDC_SEND_DATA                   1002
#define IDC_OPEN_DATA                   1003
#define IDC_CALL_HANGUP                 1008
#define IDC_EMAIL                       1008
#define IDC_IR_RECORD                   1008
#define IDC_TEST_PORT                   1008
#define IDC_REW                         1009
#define IDC_WEBSITE                     1009
#define IDC_IR_PLAYBACK                 1009
#define IDC_REC                         1010
#define IDC_PLAY                        1011
#define IDC_FF                          1012
#define IDC_EDIT1                       1012
#define IDC_MACHINE_NAME                1012
#define IDC_STOP                        1013
#define IDC_STATIC_ICON                 1013
#define IDC_PAUSE                       1014
#define IDC_VCR                         1015
#define IDC_POWER                       1016
#define IDC_RADIO_LPT1                  1016
#define IDC_RADIO_LPT2                  1017
#define IDC_RADIO_LPT3                  1018
#define IDC_CHECK1                      1019
#define IDC_LOCAL_MODE                  1019
#define IDC_BUTTON1                     1020
#define IDC_IR_WIZARD                   1020
#define IDC_CAMERA1                     1020
#define IDC_IR_START                    1020
#define IDC_BUTTON_HOST                 1020
#define IDC_IR_LABEL                    1021
#define IDC_CAMERA2                     1021
#define IDC_CAMERA3                     1022
#define IDC_CAMERA4                     1023
#define IDC_IR_FIRST                    1023
#define IDC_CAMERA5                     1024
#define IDC_IR_SECOND                   1024
#define IDC_CAMERA6                     1025
#define IDC_IR_THIRD                    1025
#define IDC_EDIT_COFERENCE_NAME         1025
#define IDC_CAMERA7                     1026
#define IDC_EDIT_CONFERENCE_PASSWORD    1026
#define IDC_CAMERA8                     1027
#define IDC_JOIN_CONFERENCE             1027
#define IDC_HOST_CONFERENCE             1028
#define IDC_BUTTON_CLOSE                0x02000
#define ID_CALL_HANGUP                  32773
#define ID_SEND_TEXT                    32775
#define ID_CONTROL_SHEET                32776
#define IDS_TAB_CAMERA_CONTROL          57665
#define IDS_TAB_VCR_CONTROL             57666
#define IDS_TAB_CALL_CONTROL            57667
#define IDS_TAB_REMOTE_CONTROL          57668
#define IDS_TAB_SETTINGS                57669
#define IDS_MACHINE_NAME                57670

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        198
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
