#if !defined(AFX_CONTROLCM_H__ED9B34DF_267C_40A6_BAD2_A6A1CC7F59E8__INCLUDED_)
#define AFX_CONTROLCM_H__ED9B34DF_267C_40A6_BAD2_A6A1CC7F59E8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CControlCM wrapper class

class CControlCM : public CWnd
{
protected:
	DECLARE_DYNCREATE(CControlCM)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x5e41955f, 0x1ded, 0x11d3, { 0xaa, 0x97, 0x0, 0x60, 0x97, 0xc0, 0xe8, 0xc9 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	short GetComport();
	void SetComport(short nNewValue);
	void ResetCom();
	void Exec(BSTR* housecode, BSTR* devicecode, short* command, short* brightness);
	// method 'SendToCM17' not emitted because of invalid return type or parameter type
	short Init();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CONTROLCM_H__ED9B34DF_267C_40A6_BAD2_A6A1CC7F59E8__INCLUDED_)
